spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.110/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  logging:
#    pattern:
#      console: "%d - %msg%n"
#    path: /var/log/tomcat/sell.log
#    level: debug

# Server root path
server:
  servlet:
    context-path: /sell